FROM alpine:3.16 AS builder

ARG THREADS=4
WORKDIR /

RUN apk add --no-cache \
    git g++ build-base linux-headers cmake python3 py3-pip pkgconf \
    curl-dev rapidjson-dev pcre2-dev yaml-cpp-dev

RUN git clone https://github.com/ftk/quickjspp --depth=1 && \
    cd quickjspp && \
    git submodule update --init && \
    cmake -DCMAKE_BUILD_TYPE=Release . && \
    make quickjs -j "$THREADS" && \
    install -d /usr/lib/quickjs/ /usr/include/quickjs/ && \
    install -m644 quickjs/libquickjs.a /usr/lib/quickjs/ && \
    install -m644 quickjs/quickjs.h quickjs/quickjs-libc.h /usr/include/quickjs/ && \
    install -m644 quickjspp.hpp /usr/include

RUN git clone https://github.com/PerMalmberg/libcron --depth=1 && \
    cd libcron && \
    git submodule update --init && \
    cmake -DCMAKE_BUILD_TYPE=Release . && \
    make libcron -j "$THREADS" && \
    install -m644 libcron/out/Release/liblibcron.a /usr/lib/ && \
    install -d /usr/include/libcron/ /usr/include/date/ && \
    install -m644 libcron/include/libcron/* /usr/include/libcron/ && \
    install -m644 libcron/externals/date/include/date/* /usr/include/date/

RUN git clone https://github.com/ToruNiina/toml11 --branch=v4.3.0 --depth=1 && \
    cd toml11 && \
    cmake -DCMAKE_CXX_STANDARD=11 . && \
    make install -j "$THREADS"

COPY tindy-subconverter /subconverter
WORKDIR /subconverter

RUN cmake -DCMAKE_BUILD_TYPE=Release . && \
    make -j "$THREADS"

FROM alpine:3.16
RUN apk add --no-cache pcre2 libcurl yaml-cpp
COPY --from=builder /subconverter/subconverter /subconverter
COPY --from=builder /subconverter/base /base
